jupyter_book_task:
  container:
    dockerfile: .ci/Dockerfile
    cpu: 4
    memory: 12G
  build_script: |
    find docs -type f -name "*.ipynb" -print0 | parallel -0 -j4 jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=1000 --execute --allow-errors --inplace {}
    jupyter-book build docs -v
  # pages_script: |
  #   if [[ $CIRRUS_BRANCH == "main" ]]; then
  #     ghp-import -n docs/_build/html
  #     git push -fq https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git gh-pages
  #   fi
