jupyter_book_task:
  auto_cancellation: true
  container:
    image: ghcr.io/sosiristseng/docker-juliabook:1.7.3.4
    cpu: 4
    memory: 16G
    use_in_memory_disk: true
  julia_cache:
    folder: ~/.julia
    fingerprint_script:
      - cat Project.toml
      - cat Manifest.toml
  install_script: |
    julia --threads=auto --project=@. --color=yes -e 'import Pkg; Pkg.instantiate()'
    julia --threads=auto --project=@. --color=yes build.jl
  build_script: |
    find docs -type f -name "*.ipynb" -print0 | parallel -0 -j4 jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=1000 --execute --inplace {}
    jupyter-book build docs -v
  # pages_script: |
  #   if [[ $CIRRUS_BRANCH == "main" ]]; then
  #     ghp-import -n docs/_build/html
  #     git push -fq https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git gh-pages
  #   fi
