variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - build
  - test
  - deploy

# GitLab CI: Auto dependency updates https://thacoon.com/posts/gitlab-ci-auto-dependency-update/
# You need a personal access token as GIT_PUSH_TOKEN, with api and write repository rights
update-julia-notebooks:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  image: python:3.10-slim
  tags:
    - "md705"
  variables:
    JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia"
    JL_MAJOR: "1.7"
    JL_MINOR: "1"
    JL_ARCH: "x64"
    JULIA_PATH: "/usr/local"
    N_CORES: 8
  cache:
    - key:
        files:
          - requirements.txt
      paths:
        - venv/
        - .cache/pip
    - key: julia-$JL_MAJOR
      paths:
        - .julia/artifacts
        - .julia/compiled
        - .julia/packages

  before_script:
    - pip install -U pip wheel virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - apt-get -qq update && apt-get -qq install parallel git curl > /dev/null
    - curl -fL "https://julialang-s3.julialang.org/bin/linux/${JL_ARCH}/${JL_MAJOR}/julia-${JL_MAJOR}.${JL_MINOR}-linux-x86_64.tar.gz" | tar -xzf - -C "${JULIA_PATH}" --strip-components 1
    - julia --version
    - julia --color=yes --threads=auto -e 'import Pkg; Pkg.add(["IJulia", "PyPlot"]); Pkg.build(["IJulia", "PyPlot"]); import PyPlot'
    - julia --color=yes --threads=auto --project=@. -e 'import Pkg; Pkg.update()'
    - find docs -type f -name "*.ipynb" -print0 | parallel -0 -j${N_CORES} jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --ExecutePreprocessor.kernel_name=julia-${JL_MAJOR} --execute --inplace {}
    - |
      if [[ -n $(git status --porcelain) ]]; then
        echo "Commiting updates"
        NEW_BR=auto-update-$(date '+%Y-%m-%d-%H-%M-%S')
        git config --global user.name "${GITLAB_USER_NAME}"
        git config --global user.email "${GITLAB_USER_EMAIL}"
        git checkout -b ${NEW_BR}
        git add .
        git commit -m "${NEW_BR}"
        git push "https://${GITLAB_USER_NAME}:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" \
            -o merge_request.create \
            -o merge_request.target="${CI_DEFAULT_BRANCH}" \
            -o merge_request.merge_when_pipeline_succeeds \
            -o merge_request.remove_source_branch \
            -o merge_request.title="${NEW_BR}" \
            -o merge_request.label="automated update" \
            -o merge_request.assign="${GITLAB_USER_NAME}"
        exit;
      else
        echo "no change, nothing to commit"
      fi

build-notebooks:
  stage: build
  image: python:3.10-slim
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  cache:
    - key:
        files:
          - .jb/requirements.txt
      paths:
        - venv/
        - .cache/pip
  before_script:
    - pip install -U pip wheel virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r .jb/requirements.txt
  script:
    - jupyter-book build docs
  artifacts:
    paths:
      - docs/_build/

pages:
  stage: deploy
  image: alpine:3.15
  needs: ["build-notebooks"]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
  script:
    - mv docs/_build/html public
    - apk add --no-cache brotli gzip
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip   -f -k {} \; || echo 'Gzip failed. Skipping...'
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec brotli -f -k {} \; || echo 'Brotli failed. Skipping...'
  artifacts:
    paths:
      - public
