name = "Startup"
uuid = "a62b76ab-7d3f-4675-a0a2-3db7dd0a15ab"
version = "0.1.0"
authors = ["Wen Wei Tseng <sosiristseng@gmail.com>"]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1"
