name: Jupyter Book Website

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write
  pull-requests: write

env:
  NPROC: '2'
  JULIA_DEPOT_PATH: '/srv/juliapkgs'
  JULIA_CACHE: '2'
  PYTHON_VER: '3.11'

jobs:
  literate:
    runs-on: ubuntu-latest
    container:
      image: julia:1.8.5
      env:
        JULIA_NUM_THREADS: 'auto'
        PYTHON: ""
        JULIA_PROJECT: ${{ github.workspace }}
        GKSwstype: 100
    steps:
      - name: Install git
        run: apt-get update -q && apt-get install git -y --no-install-recommends
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache Julia dependencies
        uses: actions/cache@v3
        if: ${{ env.JULIA_CACHE != '0'}}
        with:
          path: ${{ env.JULIA_DEPOT_PATH }}
          key: ${{ runner.os }}-julia-${{ env.JULIA_CACHE }}-${{ hashFiles('**/Manifest.toml') }}
      - name: Install Julia dependencies
        run: julia --color=yes -e 'import Pkg; Pkg.UPDATED_REGISTRY_THIS_SESSION[] = true; Pkg.instantiate(); Pkg.resolve(); Pkg.precompile()'
      - name: Build notebooks with ${{ env.NPROC }} processes
        run: julia --color=yes -p ${{ env.NPROC }} literate.jl
      - name: Deploy Notebooks
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: out
          force_orphan: true

  jupyter-book:
    needs: literate
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: out
      - name: Setup Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v4
        id: python
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Build website
        run: pipx run jupyter-book build docs/
      - name: Upload pages artifact
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_build/html

  # Deployment to GH pages
  deploy:
    needs: jupyter-book
    if: ${{ github.ref == 'refs/heads/main' }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  binder:
    needs: literate
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout jupyter notebook branch
      uses: actions/checkout@v3
      with:
        ref: out
    - name: repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_REGISTRY: ghcr.io
        DOCKER_USERNAME: ${{ github.repository_owner }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_NAME: ${{ github.repository }}
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
        ADDITIONAL_TAG: "binder"
        LATEST_TAG_OFF: true
