name: Check markdown links

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * 1"  # Every Monday

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Jupyter book Dependencies
        run: pip install -r _jb/requirements.txt
      - name: Check links
        run: jb build . --builder linkcheck