name: Auto update notebooks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"  # Every Tuesday

jobs:
  pkgupd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Cache python
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-
      - name: Cache Julia
        uses: actions/cache@v2
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-${{ hashFiles('**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-
      - name: Install dependencies
        run: |
          pip install jupyter nbconvert
          julia --color=yes -e 'using Pkg; Pkg.add("IJulia"); Pkg.build("IJulia");'
          julia --project=docs/abm/ --color=yes -e 'using Pkg; Pkg.update()'
          julia --project=docs/intro/ --color=yes -e 'using Pkg; Pkg.update()'
          julia --project=docs/mmsb/ --color=yes -e 'using Pkg; Pkg.update()'
      - name: run notebooks
        run: 'find . -type f -name "*.ipynb" -print0 | parallel -0 -j$(nproc) jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --inplace {}'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3